name: Push

on:
  push:
    branches:
      - main
      - next

jobs:
  test:
    uses: morpho-labs/ethers-multicall/.github/workflows/test.yml@main

  release:
    needs: test

    uses: morpho-labs/ethers-multicall/.github/workflows/release.yml@main
    secrets: inherit
